baseURL = '/'
languageCode = 'en-us'
title = "aniko33"
theme = "smol"
paginate = 5
pluralizelisttitles = false 

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static/imgs'
target = 'assets/imgs'

# Parameters
[params]
    subtitle = "Veni Vidi Vici"
    dateFmt = "02.01.2006"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/aniko33"
        weight = 1 

    [[menu.footer]]
        name = "X/Twitter"
        url = "https://x.com/MrAnik00"
        weight = 2 

